reset :-
	terminal_set("window: size=80x25, cellsize=auto, title='Omni: menu'; font=default"),
	terminal_color(color(255, 255, 255, 255));

run(Entries) :-
	terminal_clear,
	forall((member(entry(Text, Pred)), Entries), print_entry(Text)),
	terminal_print(2, 23, "[color=orange]ESC.[/color] Exit"),
	terminal_refresh,
	terminal_read(Key),
	(
		((Key >= 0x1E, Key =< 0x26) ; (Key >= 0x04, Key =< 0x1D)),
		(Key >= 0x1E, Index is Key - 0x1E ; Index is 9 + (Key - 0x04)),
		Index >= 0,
		Index < length(Entries),
		nth0(Index, Entries, Pred),
		call(Pred),
		reset,
		run(Entries)
		;
		(Key = 0x28 ; Key = 0xE0)
		;
		run(Entries)
	).

go :-
	reset,
	run([
		entry("Basic output", testBasicOutput),
		entry("Default font", testDefaultFont),
		entry("Tilesets", testTilesets),
		entry("Sprites", testSprites),
		entry("Manual cellsize", testManualCellsize),
		entry("Auto-generated tileset", testAutoGenerated),
		entry("Multiple fonts", testMultipleFonts),
		entry("Text alignment", testTextAlignment),
		entry("Formatted log", testFormattedLog),
		entry("Layers", testLayers),
		entry("Extended 1: basics", testExtendedBasics),
		entry("Extended 2: smooth scroll", testExtendedSmoothScroll),
		entry("Dynamic sprites", testDynamicSprites),
		entry("Speed", testSpeed),
		entry("Input 1: keyboard", testKeyboard),
		entry("Input 2: mouse", testMouse),
		entry("Input 3: text input", testTextInput),
		entry("Input 4: filtering", testInputFiltering),
		entry("Window resizing", testWindowResize),
		entry("Examining cell contents", testPick)]).